#!/system/bin/sh

### BEGIN INIT INFO
# Exec: ready
# Process: new
### END INIT INFO

VERSION_NUMBER="2.0.0"

# Assign names to GPIO pin numbers
STATUS_PIN=17
SHUTDOWN_PIN=18

# Assign names to states
STATE_ON="1"
STATE_OFF="0"

doRun=$STATE_ON

setPinValue() {
  LD_LIBRARY_PATH=/data/user/libgpiod /data/user/libgpiod/gpioset --chip 4 --toggle 0 $1=$2
}

getPinValue() {
  LD_LIBRARY_PATH=/data/user/libgpiod /data/user/libgpiod/gpioget --chip 4 --numeric $1
}

doShutdown() {
  reboot -p  # Android call for shutting down the system
  doRun=$STATE_OFF
}

setPinValue "$STATUS_PIN" "$STATE_ON"

echo "[PowerBlock] Service started, version $VERSION_NUMBER"
log -p i -t "PowerBlock" "Service started, version $VERSION_NUMBER"

# Poll shutdown signal once per second
while [ "$doRun" -eq "$STATE_ON" ]; do
  sleep 1
  currentValue=$(getPinValue "$SHUTDOWN_PIN")
  if [ "$currentValue" -eq "$STATE_ON" ]; then
    echo "[PowerBlock] Shutdown signal detected."
    log -p i -t "PowerBlock" "Shutdown signal detected."
    doShutdown
  fi
done
